/**
 * Error codes for BastionAuth API
 */
export const ERROR_CODES = {
  // Authentication errors (1xxx)
  INVALID_CREDENTIALS: 'AUTH_1001',
  INVALID_TOKEN: 'AUTH_1002',
  TOKEN_EXPIRED: 'AUTH_1003',
  SESSION_NOT_FOUND: 'AUTH_1004',
  SESSION_REVOKED: 'AUTH_1005',
  MFA_REQUIRED: 'AUTH_1006',
  MFA_INVALID_CODE: 'AUTH_1007',
  MFA_NOT_ENABLED: 'AUTH_1008',
  MFA_ALREADY_ENABLED: 'AUTH_1009',
  PASSKEY_NOT_FOUND: 'AUTH_1010',
  PASSKEY_VERIFICATION_FAILED: 'AUTH_1011',
  MAGIC_LINK_EXPIRED: 'AUTH_1012',
  MAGIC_LINK_USED: 'AUTH_1013',
  PASSWORD_RESET_EXPIRED: 'AUTH_1014',
  PASSWORD_RESET_USED: 'AUTH_1015',
  OAUTH_ERROR: 'AUTH_1016',
  OAUTH_STATE_MISMATCH: 'AUTH_1017',
  OAUTH_ACCOUNT_EXISTS: 'AUTH_1018',
  OAUTH_ACCOUNT_NOT_FOUND: 'AUTH_1019',

  // User errors (2xxx)
  USER_NOT_FOUND: 'USER_2001',
  USER_ALREADY_EXISTS: 'USER_2002',
  EMAIL_ALREADY_EXISTS: 'USER_2003',
  USERNAME_ALREADY_EXISTS: 'USER_2004',
  EMAIL_NOT_VERIFIED: 'USER_2005',
  USER_LOCKED: 'USER_2006',
  USER_DELETED: 'USER_2007',
  INVALID_PASSWORD: 'USER_2008',
  PASSWORD_TOO_WEAK: 'USER_2009',
  PASSWORD_BREACHED: 'USER_2010',
  SAME_PASSWORD: 'USER_2011',
  CANNOT_DELETE_LAST_AUTH: 'USER_2012',

  // Organization errors (3xxx)
  ORGANIZATION_NOT_FOUND: 'ORG_3001',
  ORGANIZATION_ALREADY_EXISTS: 'ORG_3002',
  SLUG_ALREADY_EXISTS: 'ORG_3003',
  MEMBER_NOT_FOUND: 'ORG_3004',
  MEMBER_ALREADY_EXISTS: 'ORG_3005',
  INVITATION_NOT_FOUND: 'ORG_3006',
  INVITATION_EXPIRED: 'ORG_3007',
  INVITATION_ALREADY_ACCEPTED: 'ORG_3008',
  ROLE_NOT_FOUND: 'ORG_3009',
  ROLE_ALREADY_EXISTS: 'ORG_3010',
  CANNOT_REMOVE_OWNER: 'ORG_3011',
  CANNOT_DEMOTE_OWNER: 'ORG_3012',
  MAX_MEMBERS_REACHED: 'ORG_3013',
  DOMAIN_NOT_ALLOWED: 'ORG_3014',
  INSUFFICIENT_PERMISSIONS: 'ORG_3015',

  // Validation errors (4xxx)
  VALIDATION_ERROR: 'VAL_4001',
  INVALID_INPUT: 'VAL_4002',
  MISSING_REQUIRED_FIELD: 'VAL_4003',
  INVALID_EMAIL: 'VAL_4004',
  INVALID_URL: 'VAL_4005',
  INVALID_UUID: 'VAL_4006',

  // Rate limiting errors (5xxx)
  RATE_LIMIT_EXCEEDED: 'RATE_5001',
  TOO_MANY_REQUESTS: 'RATE_5002',
  TOO_MANY_FAILED_ATTEMPTS: 'RATE_5003',

  // Server errors (6xxx)
  INTERNAL_ERROR: 'SERVER_6001',
  DATABASE_ERROR: 'SERVER_6002',
  REDIS_ERROR: 'SERVER_6003',
  EMAIL_SEND_ERROR: 'SERVER_6004',
  ENCRYPTION_ERROR: 'SERVER_6005',

  // Webhook errors (7xxx)
  WEBHOOK_NOT_FOUND: 'WEBHOOK_7001',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_7002',
  INVALID_WEBHOOK_URL: 'WEBHOOK_7003',

  // API Key errors (8xxx)
  API_KEY_NOT_FOUND: 'API_KEY_8001',
  API_KEY_REVOKED: 'API_KEY_8002',
  API_KEY_EXPIRED: 'API_KEY_8003',
  INVALID_API_KEY: 'API_KEY_8004',
  INSUFFICIENT_SCOPE: 'API_KEY_8005',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Error messages corresponding to error codes
 */
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  // Authentication
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid or malformed token',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.SESSION_NOT_FOUND]: 'Session not found',
  [ERROR_CODES.SESSION_REVOKED]: 'Session has been revoked',
  [ERROR_CODES.MFA_REQUIRED]: 'Multi-factor authentication is required',
  [ERROR_CODES.MFA_INVALID_CODE]: 'Invalid verification code',
  [ERROR_CODES.MFA_NOT_ENABLED]: 'MFA is not enabled for this account',
  [ERROR_CODES.MFA_ALREADY_ENABLED]: 'MFA is already enabled for this account',
  [ERROR_CODES.PASSKEY_NOT_FOUND]: 'Passkey not found',
  [ERROR_CODES.PASSKEY_VERIFICATION_FAILED]: 'Passkey verification failed',
  [ERROR_CODES.MAGIC_LINK_EXPIRED]: 'Magic link has expired',
  [ERROR_CODES.MAGIC_LINK_USED]: 'Magic link has already been used',
  [ERROR_CODES.PASSWORD_RESET_EXPIRED]: 'Password reset link has expired',
  [ERROR_CODES.PASSWORD_RESET_USED]: 'Password reset link has already been used',
  [ERROR_CODES.OAUTH_ERROR]: 'OAuth authentication failed',
  [ERROR_CODES.OAUTH_STATE_MISMATCH]: 'OAuth state mismatch',
  [ERROR_CODES.OAUTH_ACCOUNT_EXISTS]: 'This OAuth account is already linked to another user',
  [ERROR_CODES.OAUTH_ACCOUNT_NOT_FOUND]: 'OAuth account not found',

  // User
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists',
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Email is already in use',
  [ERROR_CODES.USERNAME_ALREADY_EXISTS]: 'Username is already taken',
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Email address has not been verified',
  [ERROR_CODES.USER_LOCKED]: 'Account is temporarily locked',
  [ERROR_CODES.USER_DELETED]: 'Account has been deleted',
  [ERROR_CODES.INVALID_PASSWORD]: 'Current password is incorrect',
  [ERROR_CODES.PASSWORD_TOO_WEAK]: 'Password does not meet security requirements',
  [ERROR_CODES.PASSWORD_BREACHED]:
    'This password has been found in a data breach. Please choose a different password',
  [ERROR_CODES.SAME_PASSWORD]: 'New password must be different from current password',
  [ERROR_CODES.CANNOT_DELETE_LAST_AUTH]:
    'Cannot remove the last authentication method. Add another method first',

  // Organization
  [ERROR_CODES.ORGANIZATION_NOT_FOUND]: 'Organization not found',
  [ERROR_CODES.ORGANIZATION_ALREADY_EXISTS]: 'Organization already exists',
  [ERROR_CODES.SLUG_ALREADY_EXISTS]: 'Organization slug is already taken',
  [ERROR_CODES.MEMBER_NOT_FOUND]: 'Member not found',
  [ERROR_CODES.MEMBER_ALREADY_EXISTS]: 'User is already a member of this organization',
  [ERROR_CODES.INVITATION_NOT_FOUND]: 'Invitation not found',
  [ERROR_CODES.INVITATION_EXPIRED]: 'Invitation has expired',
  [ERROR_CODES.INVITATION_ALREADY_ACCEPTED]: 'Invitation has already been accepted',
  [ERROR_CODES.ROLE_NOT_FOUND]: 'Role not found',
  [ERROR_CODES.ROLE_ALREADY_EXISTS]: 'Role with this key already exists',
  [ERROR_CODES.CANNOT_REMOVE_OWNER]: 'Cannot remove the organization owner',
  [ERROR_CODES.CANNOT_DEMOTE_OWNER]: 'Cannot change the role of the organization owner',
  [ERROR_CODES.MAX_MEMBERS_REACHED]: 'Organization has reached its member limit',
  [ERROR_CODES.DOMAIN_NOT_ALLOWED]:
    'Your email domain is not allowed to join this organization',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]:
    'You do not have permission to perform this action',

  // Validation
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation error',
  [ERROR_CODES.INVALID_INPUT]: 'Invalid input provided',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Missing required field',
  [ERROR_CODES.INVALID_EMAIL]: 'Invalid email address',
  [ERROR_CODES.INVALID_URL]: 'Invalid URL',
  [ERROR_CODES.INVALID_UUID]: 'Invalid UUID format',

  // Rate limiting
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded. Please try again later',
  [ERROR_CODES.TOO_MANY_REQUESTS]: 'Too many requests. Please slow down',
  [ERROR_CODES.TOO_MANY_FAILED_ATTEMPTS]:
    'Too many failed attempts. Please try again later',

  // Server
  [ERROR_CODES.INTERNAL_ERROR]: 'An internal error occurred',
  [ERROR_CODES.DATABASE_ERROR]: 'Database error occurred',
  [ERROR_CODES.REDIS_ERROR]: 'Cache error occurred',
  [ERROR_CODES.EMAIL_SEND_ERROR]: 'Failed to send email',
  [ERROR_CODES.ENCRYPTION_ERROR]: 'Encryption error occurred',

  // Webhook
  [ERROR_CODES.WEBHOOK_NOT_FOUND]: 'Webhook not found',
  [ERROR_CODES.WEBHOOK_DELIVERY_FAILED]: 'Webhook delivery failed',
  [ERROR_CODES.INVALID_WEBHOOK_URL]: 'Invalid webhook URL',

  // API Key
  [ERROR_CODES.API_KEY_NOT_FOUND]: 'API key not found',
  [ERROR_CODES.API_KEY_REVOKED]: 'API key has been revoked',
  [ERROR_CODES.API_KEY_EXPIRED]: 'API key has expired',
  [ERROR_CODES.INVALID_API_KEY]: 'Invalid API key',
  [ERROR_CODES.INSUFFICIENT_SCOPE]: 'API key does not have sufficient scope',
};

/**
 * HTTP status codes for error codes
 */
export const ERROR_STATUS_CODES: Record<ErrorCode, number> = {
  // Authentication - 401
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.INVALID_TOKEN]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.SESSION_NOT_FOUND]: 401,
  [ERROR_CODES.SESSION_REVOKED]: 401,
  [ERROR_CODES.MFA_REQUIRED]: 403,
  [ERROR_CODES.MFA_INVALID_CODE]: 401,
  [ERROR_CODES.MFA_NOT_ENABLED]: 400,
  [ERROR_CODES.MFA_ALREADY_ENABLED]: 400,
  [ERROR_CODES.PASSKEY_NOT_FOUND]: 404,
  [ERROR_CODES.PASSKEY_VERIFICATION_FAILED]: 401,
  [ERROR_CODES.MAGIC_LINK_EXPIRED]: 410,
  [ERROR_CODES.MAGIC_LINK_USED]: 410,
  [ERROR_CODES.PASSWORD_RESET_EXPIRED]: 410,
  [ERROR_CODES.PASSWORD_RESET_USED]: 410,
  [ERROR_CODES.OAUTH_ERROR]: 401,
  [ERROR_CODES.OAUTH_STATE_MISMATCH]: 400,
  [ERROR_CODES.OAUTH_ACCOUNT_EXISTS]: 409,
  [ERROR_CODES.OAUTH_ACCOUNT_NOT_FOUND]: 404,

  // User - 400/404/409
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 409,
  [ERROR_CODES.USERNAME_ALREADY_EXISTS]: 409,
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 403,
  [ERROR_CODES.USER_LOCKED]: 423,
  [ERROR_CODES.USER_DELETED]: 410,
  [ERROR_CODES.INVALID_PASSWORD]: 400,
  [ERROR_CODES.PASSWORD_TOO_WEAK]: 400,
  [ERROR_CODES.PASSWORD_BREACHED]: 400,
  [ERROR_CODES.SAME_PASSWORD]: 400,
  [ERROR_CODES.CANNOT_DELETE_LAST_AUTH]: 400,

  // Organization - 400/403/404/409
  [ERROR_CODES.ORGANIZATION_NOT_FOUND]: 404,
  [ERROR_CODES.ORGANIZATION_ALREADY_EXISTS]: 409,
  [ERROR_CODES.SLUG_ALREADY_EXISTS]: 409,
  [ERROR_CODES.MEMBER_NOT_FOUND]: 404,
  [ERROR_CODES.MEMBER_ALREADY_EXISTS]: 409,
  [ERROR_CODES.INVITATION_NOT_FOUND]: 404,
  [ERROR_CODES.INVITATION_EXPIRED]: 410,
  [ERROR_CODES.INVITATION_ALREADY_ACCEPTED]: 410,
  [ERROR_CODES.ROLE_NOT_FOUND]: 404,
  [ERROR_CODES.ROLE_ALREADY_EXISTS]: 409,
  [ERROR_CODES.CANNOT_REMOVE_OWNER]: 403,
  [ERROR_CODES.CANNOT_DEMOTE_OWNER]: 403,
  [ERROR_CODES.MAX_MEMBERS_REACHED]: 403,
  [ERROR_CODES.DOMAIN_NOT_ALLOWED]: 403,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,

  // Validation - 400
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.INVALID_INPUT]: 400,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_EMAIL]: 400,
  [ERROR_CODES.INVALID_URL]: 400,
  [ERROR_CODES.INVALID_UUID]: 400,

  // Rate limiting - 429
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  [ERROR_CODES.TOO_MANY_FAILED_ATTEMPTS]: 429,

  // Server - 500
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.REDIS_ERROR]: 500,
  [ERROR_CODES.EMAIL_SEND_ERROR]: 500,
  [ERROR_CODES.ENCRYPTION_ERROR]: 500,

  // Webhook - 400/404
  [ERROR_CODES.WEBHOOK_NOT_FOUND]: 404,
  [ERROR_CODES.WEBHOOK_DELIVERY_FAILED]: 500,
  [ERROR_CODES.INVALID_WEBHOOK_URL]: 400,

  // API Key - 401/403
  [ERROR_CODES.API_KEY_NOT_FOUND]: 404,
  [ERROR_CODES.API_KEY_REVOKED]: 401,
  [ERROR_CODES.API_KEY_EXPIRED]: 401,
  [ERROR_CODES.INVALID_API_KEY]: 401,
  [ERROR_CODES.INSUFFICIENT_SCOPE]: 403,
};

